nacos:
  config:
    auto-refresh: true
    config-retry-time: 3000
    namespace: common
    group: DEFAULT_GROUP
    enable-remote-sync-config: true
    type: yaml
    data-ids: common-server,common-datasource,common-global-properties,common-mybatis-plus,common-redis,common-mail,common-rocketmq,common-xxl-job,common-ids,common-fdfs,common-ext-sms
    ext-config:
      - namespace: group-purchase-manager
        dataId: property-source
        group: dev
        type: properties
        auto-refresh: true
      - namespace: group-purchase-manager
        dataId: app-authentication
        group: dev
        type: yaml
        auto-refresh: true
