### 发送验证码， 先有验证码，后续才能发送短信
POST http://localhost:8083/group-purchase-manage/common/generateCaptcha
Content-Type: application/json

# CLICK_WORDS MATH PIC_SLIDE
{
  "captchaType": "CLICK_WORDS"
}


### 校验验证码
POST http://localhost:8083/group-purchase-manage/common/checkCaptcha
Content-Type: application/json

{
  "captchaType": "CLICK_WORDS",
  "uuid": "bd6347fe7f1f40c48daf1aa8a4afede6",
  "verifyCode": "[{\"secretKey\":\"null\",\"x\":100,\"y\":40},{\"secretKey\":\"null\",\"x\":148,\"y\":67},{\"secretKey\":\"null\",\"x\":203,\"y\":125}]"
}

### 发送手机验证码
POST http://localhost:8083/group-purchase-manage/common/sendSmsCode
Content-Type: application/json

{
  "mobile": "111111",
  "captchaVerifyRequest": {
    "uuid": "ca9f54317cff4cfd82826591aa489510",
    "verifyCode": "[{\"secretKey\":\"null\",\"x\":46,\"y\":73},{\"secretKey\":\"null\",\"x\":159,\"y\":33},{\"secretKey\":\"null\",\"x\":202,\"y\":55}]",
    "captchaType": "CLICK_WORDS",
    "captchaVerification": "bd6347fe7f1f40c48daf1aa8a4afede6---[{\"secretKey\":\"null\",\"x\":100,\"y\":40},{\"secretKey\":\"null\",\"x\":148,\"y\":67},{\"secretKey\":\"null\",\"x\":203,\"y\":125}]"
  }
}

### 查询字典
GET http://localhost:8083/group-purchase-manage/common/listDict?dictType=LOGIN_TYPE
Content-Type: application/json
Authorization: Bearer $2a$10$N9pRiN1.ooJ7dpxaNoqtFeBH6AQE/7OkodW0Gk9GW3XtcLiTfMgf2<=>d45b256b0b88de9e5cbd1332db5b8d9a3c74fb771678a07ea5ac1dcfd427759704d29645830e3ee05aaa6db04b4b43ef48ee86811c3bd506203ea42ac63d67d99a01600e8229679679f15f695d436837a4e78cf07d5e3e787a228a0ae212b2b0732751e97494bd4eddedbbb8c41d6f603f3933599f0f14a8b2d148475748546e8c5632f0e3430582662a2f18f2ef8b2ffa09a7ae72f8bf080f65431a846d57e0ff1e6acca77fb20d579e83fcd4375070


### 发送注册验证码
POST http://localhost:8083/group-purchase-manage/auth/sendRegisterSmsCode
Content-Type: application/json

{
  "mobile": "111111",
  "captchaVerifyRequest": {
    "uuid": "ca9f54317cff4cfd82826591aa489510",
    "verifyCode": "[{\"secretKey\":\"null\",\"x\":46,\"y\":73},{\"secretKey\":\"null\",\"x\":159,\"y\":33},{\"secretKey\":\"null\",\"x\":202,\"y\":55}]",
    "captchaType": "CLICK_WORDS",
    "captchaVerification": "7d4ff808746a473994c7c22ca3118f79---[{\"secretKey\":\"null\",\"x\":101,\"y\":49},{\"secretKey\":\"null\",\"x\":152,\"y\":33},{\"secretKey\":\"null\",\"x\":203,\"y\":31}]"
  }
}

### 注册
POST http://localhost:8083/group-purchase-manage/auth/registry
Accept: application/json
Content-Type: application/json

{
  "communityId": 1,
  "buildingNo": 295,
  "roomNo": 909,
  "mobile": "111111",
  "uuid": "tsr339yxaj3hipeq",
  "mobileCode": "150002",
  "password": "Aa&123456"
}


### 密码登录
POST http://localhost:8083/group-purchase-manage/auth/login
Accept: application/json
Content-Type: application/json

{
  "loginType": "PASSWORD",
  "loginIdentity": "123456789",
  "credential": "123456789"
}

### 获取当前用户认证信息
GET http://localhost:8083/group-purchase-manage/auth/currentUser
Accept: application/json
Content-Type: application/json
Authorization: Bearer $2a$10$toZ9n0t0DNwcW4sxADzsnOYZQKwAJZ9LJ32TPZTwXS1gLGuImH2QO<=>a9948a6c682cdef5fd59c5a9c67c8d33770ca3d44d43ba48f249c85b2fff5040fd37807c6dd9d97b3b4388033e4ff5ce4755413c26d3e3ba145c8a26b95358fe413ef8f2afc13aeee167a4b2e1bf3e37c16485ac1af4a15369477cb4cffed5b98a1f95e25dc7e985d1e5f38417591c3f2f376d48d44d82000599b92f558097882c2f40a15b90f860395df217bf5e4e38d4e9497adea9e8d88cb776f3ebc2d99d44f3e950e309fa770c351d3c06a84210


### 使用短信验证码登录
POST http://localhost:8083/group-purchase-manage/auth/login
Accept: application/json
Content-Type: application/json

{
  "loginType": "SMS_CODE",
  "loginIdentity": "111111",
  "credential": "000000",
  "uuid": "tsr339yxaj3hipeq"
}

